<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22108" started-at="2018-06-11T15:54:22Z" finished-at="2018-06-11T15:54:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22108" started-at="2018-06-11T15:54:22Z" finished-at="2018-06-11T15:54:44Z">
      <class name="SeleniumTest.gmail.tests.GMailTest">
        <test-method status="PASS" signature="before()[pri:0, instance:SeleniumTest.gmail.tests.GMailTest@1593948d]" name="before" is-config="true" duration-ms="4375" started-at="2018-06-11T12:54:22Z" finished-at="2018-06-11T12:54:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="gmailAccountTest()[pri:0, instance:SeleniumTest.gmail.tests.GMailTest@1593948d]" name="gmailAccountTest" duration-ms="9327" started-at="2018-06-11T12:54:26Z" finished-at="2018-06-11T12:54:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gmailAccountTest -->
        <test-method status="PASS" signature="destroy()[pri:0, instance:SeleniumTest.gmail.tests.GMailTest@1593948d]" name="destroy" is-config="true" duration-ms="837" started-at="2018-06-11T12:54:36Z" finished-at="2018-06-11T12:54:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroy -->
        <test-method status="PASS" signature="before()[pri:0, instance:SeleniumTest.gmail.tests.GMailTest@1593948d]" name="before" is-config="true" duration-ms="4142" started-at="2018-06-11T12:54:36Z" finished-at="2018-06-11T12:54:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="failedLoginTest()[pri:0, instance:SeleniumTest.gmail.tests.GMailTest@1593948d]" name="failedLoginTest" duration-ms="2610" started-at="2018-06-11T12:54:41Z" depends-on-methods="SeleniumTest.gmail.tests.GMailTest.gmailAccountTest" finished-at="2018-06-11T12:54:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Failed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Failed expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at SeleniumTest.gmail.tests.GMailTest.failedLoginTest(GMailTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedLoginTest -->
        <test-method status="PASS" signature="destroy()[pri:0, instance:SeleniumTest.gmail.tests.GMailTest@1593948d]" name="destroy" is-config="true" duration-ms="793" started-at="2018-06-11T12:54:43Z" finished-at="2018-06-11T12:54:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroy -->
      </class> <!-- SeleniumTest.gmail.tests.GMailTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
